import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Data Processing Addendum",
  description:
    "Data Processing Addendum (DPA) for MandirOS — temple trusts as controllers, MandirOS as processor.",
}

export default function DataProcessingAddendumPage() {
  return (
    <main className="gradient-hero min-h-[80vh]">
      <article className="page-container py-10 sm:py-14 max-w-3xl">
        <p className="text-xs font-semibold uppercase tracking-wide text-saffron-600 mb-2">
          Legal
        </p>
        <h1 className="text-3xl sm:text-4xl font-bold text-sacred-maroon tracking-tight">
          Data Processing Addendum
        </h1>
        <p className="text-sm text-stone-500 mt-2 mb-8">
          Last updated: 13 July 2026 · Companion to{" "}
          <Link href="/legal/privacy" className="text-saffron-700 hover:underline">
            Privacy Policy
          </Link>{" "}
          and{" "}
          <Link href="/legal/terms" className="text-saffron-700 hover:underline">
            Terms
          </Link>
        </p>

        <div className="space-y-4 text-stone-700 text-sm sm:text-base leading-relaxed">
          <p className="rounded-xl border border-saffron-100 bg-saffron-50/80 p-4 text-sm">
            This DPA applies when a temple trust (or organisation) uses MandirOS under a paid
            or free plan and MandirOS processes personal data on the temple’s instructions.
            It is a standard commercial template — not a substitute for legal counsel for
            large trusts or cross-border special cases.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">1. Parties & roles</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              <strong>Controller:</strong> the temple trust / organisation that decides why
              and how devotee and staff data are used for temple operations (donations,
              sevas, receipts, transparency).
            </li>
            <li>
              <strong>Processor:</strong> MandirOS operators, who host and process that data
              to provide the Platform as described in the Terms and product docs.
            </li>
          </ul>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">2. Subject matter</h2>
          <p>
            Processing of personal data entered into or generated by MandirOS for the
            Controller’s tenant(s), including account, donation, booking, cash-desk, check-in,
            and operational notification data, for the duration of the subscription and any
            lawful retention period thereafter.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">3. Nature & purpose</h2>
          <p>Processor shall process personal data only to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Provide multi-tenant software (donations, bookings, money desk, reports, transparency, pilgrim tools as entitled by plan);</li>
            <li>Send notifications configured by the Controller (email, Slack webhooks);</li>
            <li>Secure, backup, debug, and improve the Platform in a privacy-respecting way;</li>
            <li>Comply with law and the Controller’s documented instructions.</li>
          </ul>
          <p>
            Processor shall not sell personal data or use it for unrelated advertising.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">4. Categories of data subjects</h2>
          <p>
            Devotees/donors, seva bookers, temple staff and trustees, and other individuals
            whose data the Controller (or its staff) enters into MandirOS.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">5. Types of personal data</h2>
          <p>
            As described in the Privacy Policy: identity and contact data, payment metadata
            (not full card PAN), gotra/sankalp notes, optional tax identifiers (e.g. PAN for
            80G-style receipts), operational logs, and technical/security logs.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">6. Instructions</h2>
          <p>
            Controller instructs Processor to process data via product configuration, APIs,
            and documented support requests. Processor may refuse instructions that are
            unlawful or would compromise multi-tenant security, and will explain why.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">7. Confidentiality & staff</h2>
          <p>
            Processor ensures personnel with access are bound by confidentiality and access
            data only as needed for their role. Controllers must limit staff roles (ADMIN /
            TRUSTEE / clerk) appropriately and not share credentials.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">8. Security</h2>
          <p>
            Processor implements appropriate technical and organisational measures: HTTPS,
            access-controlled databases, role-based admin APIs, secret-protected cron jobs,
            and least-privilege operations practice. Controllers should enable strong auth
            hygiene and only invite trusted staff.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">9. Sub-processors</h2>
          <p>
            Controller authorises Processor to use infrastructure and service sub-processors
            necessary to run MandirOS, including (as configured): cloud hosting (e.g. Vercel),
            database hosting (e.g. Supabase/Postgres), payment gateways (e.g. Razorpay), email
            (e.g. Resend), SMS/OTP providers, and webhooks the Controller configures (e.g.
            Slack). A current high-level list appears in the Privacy Policy. Material changes
            to core hosting may be notified via product or admin email where practical.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">10. International transfers</h2>
          <p>
            Data may be processed in India and/or regions used by sub-processors. Processor
            will take reasonable contractual and technical steps appropriate to the transfer
            and applicable Indian law (including DPDP where relevant).
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">11. Assistance</h2>
          <p>
            Taking into account the nature of processing, Processor will reasonably assist
            Controller with data-subject requests, security incidents, and regulatory
            enquiries related to Platform-hosted data, via support channels. Controller
            remains first line for devotee requests about temple-collected data.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">12. Breach notification</h2>
          <p>
            Processor will notify Controller without undue delay after becoming aware of a
            personal data breach affecting the Controller’s tenant, with known facts and
            mitigation steps, consistent with the incident runbook and applicable law.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">13. Return & deletion</h2>
          <p>
            On termination, Controller may request export of operational data within a
            reasonable window. Processor will delete or anonymise personal data when no longer
            needed for the service or legal retention (financial/tax records may be kept
            longer as required by law). Backups expire on normal rotation.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">14. Audits</h2>
          <p>
            Upon reasonable written notice (not more than once per year, unless a breach or
            regulator requires otherwise), Processor will provide security summaries or
            questionnaires proportional to plan tier. On-site audits require mutual agreement
            and cost allocation for enterprise-scale requests.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">15. Liability & order of precedence</h2>
          <p>
            Liability limits in the Terms apply to this DPA unless mandatory law says
            otherwise. If this DPA conflicts with the Terms on data-processing topics, this
            DPA controls for those topics.
          </p>

          <h2 className="text-lg font-semibold text-sacred-maroon pt-2">16. Contact</h2>
          <p>
            DPA and privacy requests: support channels in{" "}
            <Link href="/help" className="text-saffron-700 font-medium hover:underline">
              Help
            </Link>{" "}
            · public SLA:{" "}
            <Link href="/legal/sla" className="text-saffron-700 font-medium hover:underline">
              Service levels
            </Link>
            . Include temple slug where relevant.
          </p>
        </div>
      </article>
    </main>
  )
}
